### ISSUE TITLE
Add some tests, documentation or a sample project

### ISSUE THREAD

**Issue by beeman** [mbouclas/loopback-component-image-uploads#1]
Hi @mbouclas, thanks for creating this project. It would be very handy if there was a test, some documentation or a sample project that shows how to use this component. :)

**Comment by kayazinc** [comment]
May I ask if there is any documentation or sample project for this?  Thanks!

**Comment by mbouclas** [comment]
Unfortunately, not. This was to be used for a very opinionated loopback setup
